import { images } from '../constants';

export const booksData = {
    onepiece: {
        id: 1,
        bookName: "One \n Piece",
        bookCover: images.onepiece,
        rating: "4.5/5",
        language: "Español",
        episodeNo: 1155,
        genre: ["Romance", "Adventure", "Drama"],
        readed: "120,785",
        description: "One Piece es una serie de manga japonesa escrita e ilustrada por Eiichiro Oda. Ha sido serializado en la revista de manga shōnen Weekly Shōnen Jump de Shueisha desde julio de 1997, con sus capítulos individuales compilados en 105 volúmenes de tankōbon a partir de marzo de 2023.",
        backgroundColor: "rgba(240,240,232,0.9)",
        navTintColor: "#000",
        web:"One+Piece+"
    },
    demonslayer: {
        id: 2,
        bookName: "Demon \n Slayer",
        bookCover: images.demonslayer,
        rating: "4.3/5",
        episodeNo: 289,
        genre: [
            "Adventure", "Drama"
        ],
        readed: "43,000",
        description: "Demon Slayer: Kimetsu no Yaiba es una serie de manga japonesa escrita e ilustrada por Koyoharu Gotouge. Fue serializado en la revista de manga shōnen de Shueisha Weekly Shōnen Jump desde febrero de 2016 hasta mayo de 2020, con sus capítulos recopilados en 23 volúmenes de tankōbon.",  
        web:"DemonsLayer+"
    },
    komisan: {
        id: 3,
        bookName: "Komi-san \n wa",
        bookCover: images.komisan,
        rating: "3.5/5",
        episodeNo: 382,
        genre: [
            "Drama", "Adventure", "Romance"
        ],
        readed: "83,876",
        description: "Komi Can't Communicate es una serie de manga japonesa escrita e ilustrada por Tomohito Oda. Ha sido serializado en la revista de manga shōnen Weekly Shōnen Sunday de Shogakukan desde mayo de 2016, con sus capítulos recopilados en 29 volúmenes de tankōbon a partir de abril de 2023. La serie tiene licencia en Norteamérica por Viz Media",
        backgroundColor: "rgba(119,77,143,0.9)",
        web:"Komisan+"
    },
    dragonballmultiverse: {
        id: 4,
        bookName: "Dragon ball \n Multiverse",
        bookCover: images.dragonballmultiverse,
        rating: "3.4/5",
        language: "Español",
        episodeNo: 75,
        readed: "13k",
        description: "Dragon Ball Multiverse (o DBM para abreviar) es una secuela hecha por fanáticos del Dragon Ball Manga y es un doujinshi en línea gratuito (cómic hecho por fanáticos en japonés).",  
        web:"DragonballMultiverse+"
    },
    chainsawman: {
        id: 5,
        bookName: "Chain Saw\n Man",
        bookCover: images.chainsawman,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 137,
        readed: "275k",
        description: "Chainsaw Man sigue la historia de Denji, un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita.",
        web:"chainsaw+"
    },
    jibakushounen: {
        id: 6,
        bookName: "Jibaku \n Shounen",
        bookCover: images.jibakushounen,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 119,
        readed: "275k",
        description: "Uno de los más conocidos de estos cuentos es el de Hanako-san: el fantasma de una niña que ronda los baños de la escuela. Kamome Academy tiene su propia versión",
        web:"jibakushounen+"
    },
    bluelock: {
        id: 7,
        bookName: "Blue \n Lock",
        bookCover: images.bluelock,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 227,
        readed: "25k",
        description: "Jugadores de fútbol de secundaria de todo Japón se reúnen para un controvertido proyecto diseñado para crear al mejor y más egoísta delantero del mundo.",
        web:"bluelock+"
    },
       bananafish: {
        id: 8,
        bookName: "Banana \n fish",
        bookCover: images.bananafish, 
        rating: "3.2/5",
        language: "Español",
        episodeNo: 104,
        readed: "275k",
        description: "Un chico de 17 años, miembro importante de una pandilla callejera de Nueva York, es testigo de la muerte de un hombre e intenta encontrar el significado de sus últimas palabras.",
        web:"bananafish+"
    },
    
        recordofragnarok: {
        id: 9,
        bookName: "Record of\n Ragnarok",
        bookCover: images.recordofragnarok,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 84,
        readed: "275k",
        description: "Rechazado por el egoísmo de la humanidad, el consejo vota unánimemente para destruir a todos los humanos. Pero antes de que se promulgue el decreto, Brunhilde, una de las 13 valquirias de",
        web:"Shuumatsunovalkyrie+"
    },
    
        goodnightpunpun: {
        id: 10,
        bookName: "Goodnight\n Punpun",
        bookCover: images.goodnightpunpun,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 148,
        readed: "275k",
        description: "Punpun Onodera es un niño normal de 11 años que vive en Japón. Desesperadamente idealista y romántico, Punpun comienza a ver que su vida toma un giro sutil, aunque sorprendente, hacia la edad adulta cuando conoce a la nueva chica de su clase, Aiko Tanaka.",
        web:"goodnightpunpun+"
    },
        talesofdemonsandgods: {
        id: 11,
        bookName: "Tales of Demons\n and Gods",
        bookCover: images.talesofdemonsandgods,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 355,
        readed: "275k",
        description: "Sin embargo, Nie Li, uno de los espíritus demoníacos más fuertes en su vida pasada que se encontraba en el pináculo del mundo marcial, perdió la vida.",
        web:"Talesofdemonsandgods+"
    },
    jojosbizarreadventure: {
        id: 12,
        bookName: "JoJos Bizarre \n Adventure ",
        bookCover: images.jojosbizarreadventure,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 724,
        readed: "275k",
        description: "La historia de la familia Joestar, que está poseída por una intensa fuerza psíquica, y las aventuras que cada miembro encuentra a lo largo de sus vidas.",
        web:"jojosbizarreadventure+"
    },
    spyxfamily: {
        id: 13,
        bookName: "Spy X \n Family",
        bookCover: images.spyxfamily,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 107,
        readed: "275k",
        description: "Spy × Family es una serie de manga japonesa escrita e ilustrada por Tatsuya Endo. La historia sigue a un espía que tiene que formar una familia para ejecutar una misión, sin darse cuenta de que la niña que adopta como su hija es una telépata, y la mujer con la que acepta casarse es una hábil asesina.",
        web:"spyxfamily+"
    },
  
    Berserk: {
        id: 14,
        bookName: "Berserk",
        bookCover: images.Berserk,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 216,
        readed: "275k",
        description: "la historia se centra en los personajes de Guts, un espadachín solitario, y Griffith, el líder de una banda de mercenarios llamada Band of the Hawk. Miura estrenó un prototipo de Berserk en 1988",
        web:"Berserk+"
    },
    
    blackclover: {
        id: 15,
        bookName: "Black\nclover",
        bookCover: images.blackclover,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 256,
        readed: "275k",
        description: "La historia sigue a Asta, un niño nacido sin ningún poder mágico.",
        web:"BlackClover+"
    },
    ijiranaidenagatorosan: {
        id: 16,
        bookName: "Ijiranaide \n nagatorosan ",
        bookCover: images.ijiranaidenagatorosan,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 172,
        readed: "275k",
        description: "Todos los días, Hayase Nagatoro, un estudiante de primer año que conoce en la biblioteca mientras trabaja en su manga, se burla sin descanso de Naoto Hachiouji.",
        web:"Ijiranaide+"
    },
    pumpkinnight: {
        id: 17,
        bookName: "Pumpkin \n Night",
        bookCover: images.pumpkinnight,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 97,
        readed: "275k",
        description: "El manga sigue a una chica trastornada que adopta el nombre de Noche de Calabaza cuando escapa de un hospital psiquiátrico matando a todas las enfermeras y pacientes. Ella va",
        web:"pumpkinight+"
    },
    Kaiju: {
        id: 18,
        bookName: "Kaiju",
        bookCover: images.Kaiju,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 94,
        readed: "275k",
        description: "La palabra kaiju también puede referirse a los propios monstruos gigantes, que generalmente se representan atacando ciudades importantes y luchando contra el ejército u otros monstruos. El género kaiju es un subgénero del entretenimiento tokusatsu.",
        web:"kaiju+"
    },
    Mokushiroku: {
        id: 19,
        bookName: "Mokushiroku",
        bookCover: images.Mokushiroku,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 107,
        readed: "275k",
        description: "Four Knights of the Apocalypse, también conocido como The Seven Deadly Sins: Four Knights of the Apocalypse, es una serie de manga japonesa escrita e ilustrada por Nakaba Suzuki. Es una secuela de la serie anterior de Suzuki, Los Siete Pecados Capitales.",
        web:"Mokushiroku+"
    },
    jujutsukaisen: {
        id: 20,
        bookName: "Jujutsu \n Kaisen",
        bookCover: images.jujutsukaisen,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 243,
        readed: "275k",
        description: "Entregándose ociosamente a actividades paranormales sin fundamento con el Occult Club, el estudiante de secundaria Yuuji Itadori pasa sus días en el salón del club o en el hospital.",
        web:"Jujutsukaisen+"
    },
    sonobisque: {
        id: 21,
        bookName: "Sonobisque",
        bookCover: images.sonobisque,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 96,
        readed: "275k",
        description: "un joven empobrecido que hace un contrato que fusiona su cuerpo con el de un demonio parecido a un perro llamado Pochita, otorgándole la capacidad de transformar partes de su cuerpo en motosierras",
        web:"sonobisque+"
    },
    YofukashinoUta: {
        id: 22,
        bookName: "Yofukashino \n Uta",
        bookCover: images.YofukashinoUta,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 175,
        readed: "275k",
        description: "Kou Yamori es un estudiante promedio de secundaria que lucha por comprender el complejo concepto del amor. Porque ve poco sentido en rendirse a la...",
        web:"Yofukashi+no+Uta+capítulo+"
    },
    vagabond: {
        id: 23,
        bookName: "Vagabond",
        bookCover: images.vagabond,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 327,
        readed: "275k",
        description: "Vagabond es una serie de manga épica japonesa de artes marciales escrita e ilustrada por Takehiko Inoue. Retrata un relato ficticio de la vida del espadachín japonés Musashi Miyamoto, basado en la novela Musashi de Eiji Yoshikawa.",
        web:"Vagabond+"
    },
    ShingekinoKyojin: {
        id: 24,
        bookName: "Shingekino \n Kyojin",
        bookCover: images.ShingekinoKyojin,
        rating: "3.9/5",
        language: "Español",
        episodeNo: 146,
        readed: "275k",
        description: "Attack on Titan es una serie de manga japonesa escrita e ilustrada por Hajime Isayama. Está ambientado en un mundo donde la humanidad se ve obligada a vivir en ciudades rodeadas por tres enormes muros que los protegen...",
        web:"ShingekinoKyojin+"
    },
        myheroacademia: {
        id: 25,
        bookName: "My Hero \n Academia",
        bookCover: images.myheroacademia,
        rating: "4.6/5",
        language: "Español",
        episodeNo: 444,
        readed: "275k",
        description: "Midoriya hereda el superpoder del mayor héroe del mundo, pero la grandeza no será fácil. Creado por Kohei Horikoshi.",
        web:"Boku+no+Hero+Academia+"
    },
    OnePunchMan: {
        id: 26,
        bookName: "One Punch \n Man",
        bookCover: images.OnePunchMan,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 152,
        readed: "275k",
        description: "One-Punch Man es una serie de manga de superhéroes japonesa creada por One. Cuenta la historia de Saitama, un superhéroe que, debido a que puede derrotar a cualquier oponente con un solo golpe, se aburre por la falta de desafío. Uno escribió la versión manga webcomic original a principios de 2009.",
        web:"Onepunch-Man+"},
    hunterxhunter: {
        id: 27,
        bookName: "Hunterx \n hunter",
        bookCover: images.hunterxhunter,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 404,
        readed: "275k",
        description: "Hunter × Hunter es una serie de manga japonesa escrita e ilustrada por Yoshihiro Togashi. Ha sido serializado en la revista de manga shōnen Weekly Shōnen Jump de Shueisha desde marzo de 1998, aunque el manga ha tenido pausas prolongadas con frecuencia desde 2006.",
        web:"Hunter+x+Hunter+"},
    yamada: {
        id: 28,
        bookName: "yamada",
        bookCover: images.yamada,
        rating: "3.6/5",
        language: "Español",
        episodeNo: 248,
        readed: "275k",
        description: "¡Una serie de manga yuri aclamada por la crítica! Puede que Yamada sea tímida y bastante torpe, pero los jardines de flores de su escuela siempre le han dado felicidad. De repente, ...",
        web:"Yamada+"},
   
    MushokuTensei: {
        id: 29,
        bookName: "Mushoku \n Tensei",
        bookCover: images.MushokuTensei,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 103,
        readed: "275k",
        description: "Mushoku Tensei: Jobless Reincarnation es una serie de novelas ligeras japonesas de Rifujin na Magonote e ilustradas por Shirotaka.",
        web:"Mushoku+Tensei+"},
    Mairimashita: {
        id: 30,
        bookName: "Mairimashita",
        bookCover: images.Mairimashita,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 349,
        readed: "275k",
        description: "Iruma Suzuki, de catorce años, ha sido desafortunado toda su vida, teniendo que trabajar para ganar dinero para sus padres irresponsables a pesar de ser menor de edad.",
        web:"Mairimashita+"},
    bleach: {
        id: 31,
        bookName: "Bleach",
        bookCover: images.bleach,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 364,
        readed: "275k",
        description: "Ichigo Kurosaki nunca pidió la habilidad de ver fantasmas, nació con el don. Cuando su familia es atacada por un Hollow, un alma perdida malévola, Ichigo se convierte en un Soul Reaper, dedicando su vida a proteger a los inocentes y ayudar a los espíritus torturados a encontrar la paz.",
        web:"Bleach+"},
    Dandadan: {
        id: 32,
        bookName: "Dandadan",
        bookCover: images.Dandadan,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 112,
        readed: "275k",
        description: "Momo Ayase es una chica de secundaria que cree en fantasmas pero no en extraterrestres, mientras que su compañera de clase Okarun cree en extraterrestres pero no en fantasmas. En una apuesta para determinar quién tiene razón, los dos deciden visitar por separado lugares asociados con lo oculto y lo sobrenatural.",
        web:"Dandadan+"},
    drstone: {
        id: 33,
        bookName: "Dr Stone",
        bookCover: images.drstone,
        rating: "3.4/5",
        language: "Español",
        episodeNo: 244,
        readed: "105k",
        description: "Tres milenios después de que un fenómeno misterioso convierta a cada persona en la Tierra en piedra, dos mejores amigos, un genio de la ciencia y un hombre fuerte apasionado",
        web:"Dr.Stone+"},
    kaguyasama: {
        id: 34,
        bookName: "Kaguyasama",
        bookCover: images.kaguyasama,
        rating: "3.7/5",
        language: "Español",
        episodeNo: 221,
        readed: "175k",
        description: "La presidenta del consejo estudiantil, Miyuki Shirogane, y la vicepresidenta, Kaguya Shinomiya, parecen ser la pareja perfecta, pero ambos son demasiado orgullosos para confesar su amor y planean hacer que el otro confiese su amor primero.",
        web:"Kaguya-sama+"},
    lavidadespues: {
        id: 35,
        bookName: "la vida \n despues",
        bookCover: images.lavidadespues,
        rating: "4.2/5",
        language: "Español",
        episodeNo: 187,
        readed: "275k",
        description: "La Vida Después de la Muerte es una mezcla de diferentes géneros como Drama, Acción, Aventura, Comedia, Reencarnación, Magia, Superpoderes ✓.",
        web:"La+Vida+Después+de+la+Muerte+"},
    Tsukigamichibiku : {
        id: 36,
        bookName: "Tsuki ga \n Michibiku",
        bookCover: images.Tsukigamichibiku ,
        rating: "3.2/5",
        language: "Español",
        episodeNo: 349,
        readed: "275k",
        description: "Como parte de un contrato misterioso acordado por una diosa y sus padres hace años, Makoto Misumi es enviado a otro mundo para encontrarse con la diosa.",
        web:"Tsuki+ga+Michibiku+Isekai+Douchuu+"},


}
